#!/usr/bin/env bash
# Configures Nginx with a custom HTTP response header X-Served-By set to the server hostname

sudo apt-get update -y
sudo apt-get install -y nginx

HOSTNAME=$(hostname)
echo "add_header X-Served-By \"$HOSTNAME\";" | sudo tee /etc/nginx/conf.d/custom_header.conf > /dev/null

sudo nginx -t && sudo service nginx restart