#!/usr/bin/env bash
# Install HAProxy and configure it to load balance between web-01 and web-02

# Update package list and install HAProxy
sudo apt update -y
sudo apt install -y haproxy

# Ensure HAProxy service is enabled
sudo systemctl enable haproxy

# Replace HAProxy configuration
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log local0
        log /dev/log local1 notice
	    daemon
	        maxconn 2000

		defaults
		    log     global
		        mode    http
			    option  httplog
			        option  dontlognull
				    timeout connect 5000ms
				        timeout client  50000ms
					    timeout server  50000ms

					    frontend http_front
					        bind *:80
						    default_backend http_back

						    backend http_back
						        balance roundrobin
							    server web1 18.208.109.195:80 check
							        server web2 35.175.137.170:80 check
								EOF

								# Test HAProxy config
								sudo haproxy -c -f /etc/haproxy/haproxy.cfg

								# Restart HAProxy to apply changes
								sudo systemctl restart haproxy

								# Exit 0 to indicate success
								exit 0
