#!/usr/bin/env bash
# Configure Nginx to redirect /redirect_me with a 301 status code

# Install nginx if not already installed

sudo apt update -y
sudo apt install -y nginx

# Ensure nginx is running

sudo systemctl start nginx

# Replace default server config to include redirect

sed -i '/server_name _;/a\
    location /redirect_me {\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
    }' /etc/nginx/sites-available/default

# Restart nginx to apply changes

sudo systemctl restart nginx
