#!/usr/bin/env bash
# Configure Nginx with a custom 404 page

# Install nginx

sudo apt update -y
sudo apt install -y nginx

# Start nginx

sudo systemctl start nginx

# Create custom 404 page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
echo "Ceci n'est pas une page"

# Configure nginx to use custom 404 page

sudo sed -i '/server_name _;/a\    error_page 404 /404.html;\n    location = /404.html {\n        internal;\n    }' /etc/nginx/sites-available/default

# Restart nginx

sudo systemctl restart nginx
